/** Academic Word List families (Coxhead). British headwords; EAP Foundation related forms. */
export const FAMILIES = {
  "analyse": { sublist: 1, related: ["analysed", "analyser", "analysers", "analyses", "analysing", "analysis", "analyst", "analysts", "analytic", "analytical", "analytically", "analyze", "analyzed", "analyzes", "analyzing"] },
  "approach": { sublist: 1, related: ["approachable", "approached", "approaches", "approaching", "unapproachable"] },
  "area": { sublist: 1, related: ["areas"] },
  "assess": { sublist: 1, related: ["assessable", "assessed", "assesses", "assessing", "assessment", "assessments", "reassess", "reassessed", "reassessing", "reassessment", "unassessed"] },
  "assume": { sublist: 1, related: ["assumed", "assumes", "assuming", "assumption", "assumptions"] },
  "authority": { sublist: 1, related: ["authoritative", "authorities"] },
  "available": { sublist: 1, related: ["availability", "unavailable"] },
  "benefit": { sublist: 1, related: ["beneficial", "beneficiaries", "beneficiary", "benefited", "benefiting", "benefits"] },
  "concept": { sublist: 1, related: ["conception", "concepts", "conceptual", "conceptualisation", "conceptualise", "conceptualised", "conceptualises", "conceptualising", "conceptually"] },
  "consist": { sublist: 1, related: ["consisted", "consistency", "consistent", "consistently", "consisting", "consists", "inconsistencies", "inconsistency", "inconsistent"] },
  "constitute": { sublist: 1, related: ["constituencies", "constituency", "constituent", "constituents", "constituted", "constitutes", "constituting", "constitution", "constitutional", "constitutionally", "constitutions", "constitutive", "unconstitutional"] },
  "context": { sublist: 1, related: ["contexts", "contextual", "contextualise", "contextualised", "contextualising", "contextualize", "contextualized", "contextualizing", "uncontextualised", "uncontextualized"] },
  "contract": { sublist: 1, related: ["contracted", "contracting", "contractor", "contractors", "contracts"] },
  "create": { sublist: 1, related: ["created", "creates", "creating", "creation", "creations", "creative", "creatively", "creativity", "creator", "creators", "recreate", "recreated", "recreates", "recreating"] },
  "data": { sublist: 1, related: [] },
  "define": { sublist: 1, related: ["definable", "defined", "defines", "defining", "definition", "definitions", "redefine", "redefined", "redefines", "redefining", "undefined"] },
  "derive": { sublist: 1, related: ["derivation", "derivations", "derivative", "derivatives", "derived", "derives", "deriving"] },
  "distribute": { sublist: 1, related: ["distributed", "distributing", "distribution", "distributional", "distributions", "distributive", "distributor", "distributors", "redistribute", "redistributed", "redistributes", "redistributing", "redistribution"] },
  "economy": { sublist: 1, related: ["economic", "economical", "economically", "economics", "economies", "economist", "economists", "uneconomical"] },
  "environment": { sublist: 1, related: ["environmental", "environmentalist", "environmentalists", "environmentally", "environments"] },
  "establish": { sublist: 1, related: ["disestablish", "disestablished", "disestablishes", "disestablishing", "disestablishment", "established", "establishes", "establishing", "establishment", "establishments"] },
  "estimate": { sublist: 1, related: ["estimated", "estimates", "estimating", "estimation", "estimations", "over-estimate", "overestimate", "overestimated", "overestimates", "overestimating", "underestimate", "underestimated", "underestimates", "underestimating"] },
  "evident": { sublist: 1, related: ["evidence", "evidenced", "evidential", "evidently"] },
  "export": { sublist: 1, related: ["exported", "exporter", "exporters", "exporting", "exports"] },
  "factor": { sublist: 1, related: ["factored", "factoring", "factors"] },
  "finance": { sublist: 1, related: ["financed", "finances", "financial", "financially", "financier", "financiers", "financing"] },
  "formula": { sublist: 1, related: ["formulae", "formulas", "formulate", "formulated", "formulating", "formulation", "formulations", "reformulate", "reformulated", "reformulating", "reformulation", "reformulations"] },
  "function": { sublist: 1, related: ["functional", "functionally", "functioned", "functioning", "functions"] },
  "identify": { sublist: 1, related: ["identifiable", "identification", "identified", "identifies", "identifying", "identities", "identity", "unidentifiable"] },
  "income": { sublist: 1, related: ["incomes"] },
  "indicate": { sublist: 1, related: ["indicated", "indicates", "indicating", "indication", "indications", "indicative", "indicator", "indicators"] },
  "individual": { sublist: 1, related: ["individualised", "individualism", "individualist", "individualistic", "individualists", "individuality", "individually", "individuals"] },
  "interpret": { sublist: 1, related: ["interpretation", "interpretations", "interpretative", "interpreted", "interpreting", "interpretive", "interprets", "misinterpret", "misinterpretation", "misinterpretations", "misinterpreted", "misinterpreting", "misinterprets", "reinterpret", "reinterpretation", "reinterpretations", "reinterpreted", "reinterpreting", "reinterprets"] },
  "involve": { sublist: 1, related: ["involved", "involvement", "involves", "involving", "uninvolved"] },
  "issue": { sublist: 1, related: ["issued", "issues", "issuing"] },
  "labour": { sublist: 1, related: ["labor", "labored", "labors", "laboured", "labouring", "labours"] },
  "legal": { sublist: 1, related: ["illegal", "illegality", "illegally", "legality", "legally"] },
  "legislate": { sublist: 1, related: ["legislated", "legislates", "legislating", "legislation", "legislative", "legislator", "legislators", "legislature"] },
  "major": { sublist: 1, related: ["majorities", "majority"] },
  "method": { sublist: 1, related: ["methodical", "methodological", "methodologies", "methodology", "methods"] },
  "occur": { sublist: 1, related: ["occurred", "occurrence", "occurrences", "occurring", "occurs", "reoccur", "reoccurred", "reoccurring", "reoccurs"] },
  "percent": { sublist: 1, related: ["percentage", "percentages"] },
  "period": { sublist: 1, related: ["periodic", "periodical", "periodically", "periodicals", "periods"] },
  "policy": { sublist: 1, related: ["policies"] },
  "principle": { sublist: 1, related: ["principled", "principles", "unprincipled"] },
  "proceed": { sublist: 1, related: ["procedural", "procedure", "procedures", "proceeded", "proceeding", "proceedings", "proceeds"] },
  "process": { sublist: 1, related: ["processed", "processes", "processing"] },
  "require": { sublist: 1, related: ["required", "requirement", "requirements", "requires", "requiring"] },
  "research": { sublist: 1, related: ["researched", "researcher", "researchers", "researches", "researching"] },
  "respond": { sublist: 1, related: ["responded", "respondent", "respondents", "responding", "responds", "response", "responses", "responsive", "responsiveness", "unresponsive"] },
  "role": { sublist: 1, related: ["roles"] },
  "section": { sublist: 1, related: ["sectioned", "sectioning", "sections"] },
  "sector": { sublist: 1, related: ["sectors"] },
  "significant": { sublist: 1, related: ["insignificant", "insignificantly", "significance", "significantly", "signified", "signifies", "signify", "signifying"] },
  "similar": { sublist: 1, related: ["dissimilar", "similarities", "similarity", "similarly"] },
  "source": { sublist: 1, related: ["sourced", "sources", "sourcing"] },
  "specific": { sublist: 1, related: ["specifically", "specification", "specifications", "specificity", "specifics"] },
  "structure": { sublist: 1, related: ["restructure", "restructured", "restructures", "restructuring", "structural", "structurally", "structured", "structures", "structuring", "unstructured"] },
  "theory": { sublist: 1, related: ["theoretical", "theoretically", "theories", "theorist", "theorists"] },
  "vary": { sublist: 1, related: ["invariable", "invariably", "variability", "variable", "variables", "variably", "variance", "variant", "variants", "variation", "variations", "varied", "varies", "varying"] },
  "achieve": { sublist: 2, related: ["achievable", "achieved", "achievement", "achievements", "achieves", "achieving"] },
  "acquire": { sublist: 2, related: ["acquired", "acquires", "acquiring", "acquisition", "acquisitions"] },
  "administrate": { sublist: 2, related: ["administrates", "administration", "administrations", "administrative", "administratively", "administrator", "administrators"] },
  "affect": { sublist: 2, related: ["affected", "affecting", "affective", "affectively", "affects", "unaffected"] },
  "appropriate": { sublist: 2, related: ["appropriacy", "appropriately", "appropriateness", "inappropriacy", "inappropriate", "inappropriately"] },
  "aspect": { sublist: 2, related: ["aspects"] },
  "assist": { sublist: 2, related: ["assistance", "assistant", "assistants", "assisted", "assisting", "assists", "unassisted"] },
  "category": { sublist: 2, related: ["categories", "categorisation", "categorise", "categorised", "categorises", "categorising", "categorization", "categorized", "categorizes", "categorizing"] },
  "chapter": { sublist: 2, related: ["chapters"] },
  "commission": { sublist: 2, related: ["commissioned", "commissioner", "commissioners", "commissioning", "commissions"] },
  "community": { sublist: 2, related: ["communities"] },
  "complex": { sublist: 2, related: ["complexities", "complexity"] },
  "compute": { sublist: 2, related: ["computable", "computation", "computational", "computations", "computed", "computer", "computerised", "computers", "computing"] },
  "conclude": { sublist: 2, related: ["concluded", "concludes", "concluding", "conclusion", "conclusions", "conclusive", "conclusively", "inconclusive", "inconclusively"] },
  "conduct": { sublist: 2, related: ["conducted", "conducting", "conducts"] },
  "consequent": { sublist: 2, related: ["consequence", "consequences", "consequently"] },
  "construct": { sublist: 2, related: ["constructed", "constructing", "construction", "constructions", "constructive", "constructs", "reconstruct", "reconstructed", "reconstructing", "reconstruction", "reconstructs"] },
  "consume": { sublist: 2, related: ["consumed", "consumer", "consumers", "consumes", "consuming", "consumption"] },
  "credit": { sublist: 2, related: ["credited", "crediting", "creditor", "creditors", "credits"] },
  "culture": { sublist: 2, related: ["cultural", "culturally", "cultured", "cultures", "uncultured"] },
  "design": { sublist: 2, related: ["designed", "designer", "designers", "designing", "designs"] },
  "distinct": { sublist: 2, related: ["distinction", "distinctions", "distinctive", "distinctively", "distinctly", "indistinct", "indistinctly"] },
  "element": { sublist: 2, related: ["elements"] },
  "equate": { sublist: 2, related: ["equated", "equates", "equating", "equation", "equations"] },
  "evaluate": { sublist: 2, related: ["evaluated", "evaluates", "evaluating", "evaluation", "evaluations", "evaluative", "re-evaluate", "re-evaluated", "re-evaluates", "re-evaluating", "re-evaluation"] },
  "feature": { sublist: 2, related: ["featured", "features", "featuring"] },
  "final": { sublist: 2, related: ["finalise", "finalised", "finalises", "finalising", "finality", "finalize", "finalized", "finalizes", "finalizing", "finally", "finals"] },
  "focus": { sublist: 2, related: ["focused", "focuses", "focusing", "focussed", "focussing", "refocus", "refocused", "refocuses", "refocusing", "refocussed", "refocusses", "refocussing"] },
  "impact": { sublist: 2, related: ["impacted", "impacting", "impacts"] },
  "injure": { sublist: 2, related: ["injured", "injures", "injuries", "injuring", "injury", "uninjured"] },
  "institute": { sublist: 2, related: ["instituted", "institutes", "instituting", "institution", "institutional", "institutionalise", "institutionalised", "institutionalises", "institutionalising", "institutionalized", "institutionalizes", "institutionalizing", "institutionally", "institutions"] },
  "invest": { sublist: 2, related: ["invested", "investing", "investment", "investments", "investor", "investors", "invests", "reinvest", "reinvested", "reinvesting", "reinvestment", "reinvests"] },
  "item": { sublist: 2, related: ["itemisation", "itemise", "itemised", "itemises", "itemising", "items"] },
  "journal": { sublist: 2, related: ["journals"] },
  "maintain": { sublist: 2, related: ["maintained", "maintaining", "maintains", "maintenance"] },
  "normal": { sublist: 2, related: ["abnormal", "abnormally", "normalisation", "normalise", "normalised", "normalises", "normalising", "normality", "normalization", "normalize", "normalized", "normalizes", "normalizing", "normally"] },
  "obtain": { sublist: 2, related: ["obtainable", "obtained", "obtaining", "obtains", "unobtainable"] },
  "participate": { sublist: 2, related: ["participant", "participants", "participated", "participates", "participating", "participation", "participatory"] },
  "perceive": { sublist: 2, related: ["perceived", "perceives", "perceiving", "perception", "perceptions"] },
  "positive": { sublist: 2, related: ["positively"] },
  "potential": { sublist: 2, related: ["potentially"] },
  "previous": { sublist: 2, related: ["previously"] },
  "primary": { sublist: 2, related: ["primarily"] },
  "purchase": { sublist: 2, related: ["purchased", "purchaser", "purchasers", "purchases", "purchasing"] },
  "range": { sublist: 2, related: ["ranged", "ranges", "ranging"] },
  "region": { sublist: 2, related: ["regional", "regionally", "regions"] },
  "regulate": { sublist: 2, related: ["deregulated", "deregulates", "deregulating", "deregulation", "regulated", "regulates", "regulating", "regulation", "regulations", "regulator", "regulators", "regulatory", "unregulated"] },
  "relevant": { sublist: 2, related: ["irrelevance", "irrelevant", "relevance"] },
  "reside": { sublist: 2, related: ["resided", "residence", "resident", "residential", "residents", "resides", "residing"] },
  "resource": { sublist: 2, related: ["resourced", "resourceful", "resources", "resourcing", "under-resourced", "unresourceful"] },
  "restrict": { sublist: 2, related: ["restricted", "restricting", "restriction", "restrictions", "restrictive", "restrictively", "restricts", "unrestricted", "unrestrictive"] },
  "secure": { sublist: 2, related: ["insecure", "insecurities", "insecurity", "secured", "securely", "secures", "securing", "securities", "security"] },
  "seek": { sublist: 2, related: ["seeking", "seeks", "sought"] },
  "select": { sublist: 2, related: ["selected", "selecting", "selection", "selections", "selective", "selectively", "selector", "selectors", "selects"] },
  "site": { sublist: 2, related: ["sites"] },
  "strategy": { sublist: 2, related: ["strategic", "strategically", "strategies", "strategist", "strategists"] },
  "survey": { sublist: 2, related: ["surveyed", "surveying", "surveys"] },
  "text": { sublist: 2, related: ["texts", "textual"] },
  "tradition": { sublist: 2, related: ["non-traditional", "traditional", "traditionalist", "traditionally", "traditions"] },
  "transfer": { sublist: 2, related: ["transferable", "transference", "transferred", "transferring", "transfers"] },
  "alternative": { sublist: 3, related: ["alternatively", "alternatives"] },
  "circumstance": { sublist: 3, related: ["circumstances"] },
  "comment": { sublist: 3, related: ["commentaries", "commentary", "commentator", "commentators", "commented", "commenting", "comments"] },
  "compensate": { sublist: 3, related: ["compensated", "compensates", "compensating", "compensation", "compensations", "compensatory"] },
  "component": { sublist: 3, related: ["componentry", "components"] },
  "consent": { sublist: 3, related: ["consensus", "consented", "consenting", "consents"] },
  "considerable": { sublist: 3, related: ["considerably"] },
  "constant": { sublist: 3, related: ["constancy", "constantly", "constants", "inconstancy", "inconstantly"] },
  "constrain": { sublist: 3, related: ["constrained", "constraining", "constrains", "constraint", "constraints", "unconstrained"] },
  "contribute": { sublist: 3, related: ["contributed", "contributes", "contributing", "contribution", "contributions", "contributor", "contributors"] },
  "convene": { sublist: 3, related: ["convened", "convenes", "convening", "convention", "conventional", "conventionally", "conventions", "unconventional"] },
  "coordinate": { sublist: 3, related: ["co-ordinate", "co-ordinated", "co-ordinates", "co-ordinating", "co-ordination", "co-ordinator", "co-ordinators", "coordinated", "coordinates", "coordinating", "coordination", "coordinator", "coordinators"] },
  "core": { sublist: 3, related: ["cored", "cores", "coring"] },
  "corporate": { sublist: 3, related: ["corporates", "corporation", "corporations"] },
  "correspond": { sublist: 3, related: ["corresponded", "correspondence", "corresponding", "correspondingly", "corresponds"] },
  "criteria": { sublist: 3, related: ["criterion"] },
  "deduce": { sublist: 3, related: ["deduced", "deduces", "deducing", "deduction", "deductions"] },
  "demonstrate": { sublist: 3, related: ["demonstrable", "demonstrably", "demonstrated", "demonstrates", "demonstrating", "demonstration", "demonstrations", "demonstrative", "demonstratively", "demonstrator", "demonstrators"] },
  "document": { sublist: 3, related: ["documentation", "documented", "documenting", "documents"] },
  "dominate": { sublist: 3, related: ["dominance", "dominant", "dominated", "dominates", "dominating", "domination"] },
  "emphasis": { sublist: 3, related: ["emphasise", "emphasised", "emphasising", "emphasize", "emphasized", "emphasizes", "emphasizing", "emphatic", "emphatically"] },
  "ensure": { sublist: 3, related: ["ensured", "ensures", "ensuring"] },
  "exclude": { sublist: 3, related: ["excluded", "excludes", "excluding", "exclusion", "exclusionary", "exclusionist", "exclusions", "exclusive", "exclusively"] },
  "framework": { sublist: 3, related: ["frameworks"] },
  "fund": { sublist: 3, related: ["funded", "funder", "funders", "funding", "funds"] },
  "illustrate": { sublist: 3, related: ["illustrated", "illustrates", "illustrating", "illustration", "illustrations", "illustrative"] },
  "immigrate": { sublist: 3, related: ["immigrant", "immigrants", "immigrated", "immigrates", "immigrating", "immigration"] },
  "imply": { sublist: 3, related: ["implied", "implies", "implying"] },
  "initial": { sublist: 3, related: ["initially"] },
  "instance": { sublist: 3, related: ["instances"] },
  "interact": { sublist: 3, related: ["interacted", "interacting", "interaction", "interactions", "interactive", "interactively", "interacts"] },
  "justify": { sublist: 3, related: ["justifiable", "justifiably", "justification", "justifications", "justified", "justifies", "justifying", "unjustified"] },
  "layer": { sublist: 3, related: ["layered", "layering", "layers"] },
  "link": { sublist: 3, related: ["linkage", "linkages", "linked", "linking", "links"] },
  "locate": { sublist: 3, related: ["located", "locating", "location", "locations", "relocate", "relocated", "relocates", "relocating", "relocation"] },
  "maximise": { sublist: 3, related: ["maximisation", "maximised", "maximises", "maximising", "maximization", "maximize", "maximized", "maximizes", "maximizing", "maximum"] },
  "minor": { sublist: 3, related: ["minorities", "minority", "minors"] },
  "negate": { sublist: 3, related: ["negated", "negates", "negating", "negative", "negatively", "negatives"] },
  "outcome": { sublist: 3, related: ["outcomes"] },
  "partner": { sublist: 3, related: ["partners", "partnership", "partnerships"] },
  "philosophy": { sublist: 3, related: ["philosopher", "philosophers", "philosophical", "philosophically", "philosophies", "philosophise", "philosophised", "philosophises", "philosophising", "philosophize", "philosophized", "philosophizes", "philosophizing"] },
  "physical": { sublist: 3, related: ["physically"] },
  "proportion": { sublist: 3, related: ["disproportion", "disproportionate", "disproportionately", "proportional", "proportionally", "proportionate", "proportionately", "proportions"] },
  "publish": { sublist: 3, related: ["published", "publisher", "publishers", "publishes", "publishing", "unpublished"] },
  "react": { sublist: 3, related: ["reacted", "reacting", "reaction", "reactionaries", "reactionary", "reactions", "reactivate", "reactivation", "reactive", "reactor", "reactors", "reacts"] },
  "register": { sublist: 3, related: ["deregister", "deregistered", "deregistering", "deregisters", "deregistration", "registered", "registering", "registers", "registration"] },
  "rely": { sublist: 3, related: ["reliability", "reliable", "reliably", "reliance", "reliant", "relied", "relies", "relying", "unreliable"] },
  "remove": { sublist: 3, related: ["removable", "removal", "removals", "removed", "removes", "removing"] },
  "scheme": { sublist: 3, related: ["schematic", "schematically", "schemed", "schemes", "scheming"] },
  "sequence": { sublist: 3, related: ["sequenced", "sequences", "sequencing", "sequential", "sequentially"] },
  "sex": { sublist: 3, related: ["sexes", "sexism", "sexual", "sexuality", "sexually"] },
  "shift": { sublist: 3, related: ["shifted", "shifting", "shifts"] },
  "specify": { sublist: 3, related: ["specifiable", "specified", "specifies", "specifying", "unspecified"] },
  "sufficient": { sublist: 3, related: ["insufficient", "insufficiently", "sufficiency", "sufficiently"] },
  "task": { sublist: 3, related: ["tasks"] },
  "technical": { sublist: 3, related: ["technically"] },
  "technique": { sublist: 3, related: ["techniques"] },
  "technology": { sublist: 3, related: ["technological", "technologically"] },
  "valid": { sublist: 3, related: ["invalidate", "invalidity", "validate", "validated", "validating", "validation", "validity", "validly"] },
  "volume": { sublist: 3, related: ["volumes"] },
  "access": { sublist: 4, related: ["accessed", "accesses", "accessibility", "accessible", "accessing", "inaccessible"] },
  "adequate": { sublist: 4, related: ["adequacy", "adequately", "inadequacies", "inadequacy", "inadequate", "inadequately"] },
  "annual": { sublist: 4, related: ["annually"] },
  "apparent": { sublist: 4, related: ["apparently"] },
  "approximate": { sublist: 4, related: ["approximated", "approximately", "approximates", "approximating", "approximation", "approximations"] },
  "attitude": { sublist: 4, related: ["attitudes"] },
  "attribute": { sublist: 4, related: ["attributable", "attributed", "attributes", "attributing", "attribution"] },
  "civil": { sublist: 4, related: [] },
  "code": { sublist: 4, related: ["coded", "codes", "coding"] },
  "commit": { sublist: 4, related: ["commitment", "commitments", "commits", "committed", "committing"] },
  "communicate": { sublist: 4, related: ["communicable", "communicated", "communicates", "communicating", "communication", "communications", "communicative", "communicatively", "uncommunicative"] },
  "concentrate": { sublist: 4, related: ["concentrated", "concentrates", "concentrating", "concentration"] },
  "confer": { sublist: 4, related: ["conference", "conferences", "conferred", "conferring", "confers"] },
  "contrast": { sublist: 4, related: ["contrasted", "contrasting", "contrastive", "contrasts"] },
  "cycle": { sublist: 4, related: ["cycled", "cycles", "cyclic", "cyclical", "cycling"] },
  "debate": { sublist: 4, related: ["debatable", "debated", "debates", "debating"] },
  "despite": { sublist: 4, related: [] },
  "dimension": { sublist: 4, related: ["dimensional", "dimensions", "multidimensional"] },
  "domestic": { sublist: 4, related: ["domestically", "domesticate", "domesticated", "domesticating", "domestics"] },
  "emerge": { sublist: 4, related: ["emerged", "emergence", "emergent", "emerges", "emerging"] },
  "error": { sublist: 4, related: ["erroneous", "erroneously", "errors"] },
  "ethnic": { sublist: 4, related: ["ethnicity"] },
  "goal": { sublist: 4, related: ["goals"] },
  "grant": { sublist: 4, related: ["granted", "granting", "grants"] },
  "hence": { sublist: 4, related: [] },
  "hypothesis": { sublist: 4, related: ["hypotheses", "hypothesise", "hypothesised", "hypothesises", "hypothesising", "hypothesize", "hypothesized", "hypothesizes", "hypothesizing", "hypothetical", "hypothetically"] },
  "implement": { sublist: 4, related: ["implementation", "implemented", "implementing", "implements"] },
  "implicate": { sublist: 4, related: ["implicated", "implicates", "implicating", "implication", "implications"] },
  "impose": { sublist: 4, related: ["imposed", "imposes", "imposing", "imposition"] },
  "integrate": { sublist: 4, related: ["integrated", "integrates", "integrating", "integration"] },
  "internal": { sublist: 4, related: ["internalise", "internalised", "internalises", "internalising", "internalize", "internalized", "internalizes", "internalizing", "internally"] },
  "investigate": { sublist: 4, related: ["investigated", "investigates", "investigating", "investigation", "investigations", "investigative", "investigator", "investigators"] },
  "job": { sublist: 4, related: ["jobs"] },
  "label": { sublist: 4, related: ["labeled", "labeling", "labelled", "labelling", "labels"] },
  "mechanism": { sublist: 4, related: ["mechanisms"] },
  "obvious": { sublist: 4, related: ["obviously"] },
  "occupy": { sublist: 4, related: ["occupancy", "occupant", "occupants", "occupation", "occupational", "occupations", "occupied", "occupier", "occupiers", "occupies", "occupying"] },
  "option": { sublist: 4, related: ["optional", "options"] },
  "output": { sublist: 4, related: ["outputs"] },
  "overall": { sublist: 4, related: [] },
  "parallel": { sublist: 4, related: ["paralleled", "parallelled", "parallelling", "parallels", "unparalleled"] },
  "parameter": { sublist: 4, related: ["parameters"] },
  "phase": { sublist: 4, related: ["phased", "phases", "phasing"] },
  "predict": { sublist: 4, related: ["predictability", "predictable", "predictably", "predicted", "predicting", "prediction", "predictions", "predicts", "unpredictability", "unpredictable"] },
  "principal": { sublist: 4, related: ["principally"] },
  "prior": { sublist: 4, related: [] },
  "professional": { sublist: 4, related: ["professionalism", "professionally", "professionals"] },
  "project": { sublist: 4, related: ["projected", "projecting", "projection", "projections", "projects"] },
  "promote": { sublist: 4, related: ["promoted", "promoter", "promoters", "promotes", "promoting", "promotion", "promotions"] },
  "regime": { sublist: 4, related: ["regimes"] },
  "resolve": { sublist: 4, related: ["resolution", "resolved", "resolves", "resolving", "unresolved"] },
  "retain": { sublist: 4, related: ["retained", "retainer", "retainers", "retaining", "retains", "retention", "retentive"] },
  "series": { sublist: 4, related: [] },
  "statistic": { sublist: 4, related: ["statistical", "statistically", "statistician", "statisticians", "statistics"] },
  "status": { sublist: 4, related: [] },
  "stress": { sublist: 4, related: ["stressed", "stresses", "stressful", "stressing", "unstressed"] },
  "subsequent": { sublist: 4, related: ["subsequently"] },
  "sum": { sublist: 4, related: ["summation", "summed", "summing", "sums"] },
  "summary": { sublist: 4, related: ["summaries", "summarisation", "summarisations", "summarise", "summarised", "summarises", "summarising", "summarization", "summarizations", "summarize", "summarized", "summarizes", "summarizing"] },
  "undertake": { sublist: 4, related: ["undertaken", "undertakes", "undertaking", "undertook"] },
  "academy": { sublist: 5, related: ["academia", "academic", "academically", "academics", "academies"] },
  "adjust": { sublist: 5, related: ["adjusted", "adjusting", "adjustment", "adjustments", "adjusts", "readjust", "readjusted", "readjusting", "readjustment", "readjustments", "readjusts"] },
  "alter": { sublist: 5, related: ["alterable", "alteration", "alterations", "altered", "altering", "alternate", "alternating", "alters", "unalterable", "unaltered"] },
  "amend": { sublist: 5, related: ["amended", "amending", "amendment", "amendments", "amends"] },
  "aware": { sublist: 5, related: ["awareness", "unaware"] },
  "capacity": { sublist: 5, related: ["capacities", "incapacitate", "incapacitated"] },
  "challenge": { sublist: 5, related: ["challenged", "challenger", "challengers", "challenges", "challenging"] },
  "clause": { sublist: 5, related: ["clauses"] },
  "compound": { sublist: 5, related: ["compounded", "compounding", "compounds"] },
  "conflict": { sublist: 5, related: ["conflicted", "conflicting", "conflicts"] },
  "consult": { sublist: 5, related: ["consultancy", "consultant", "consultants", "consultation", "consultations", "consultative", "consulted", "consulting", "consults"] },
  "contact": { sublist: 5, related: ["contactable", "contacted", "contacting", "contacts"] },
  "decline": { sublist: 5, related: ["declined", "declines", "declining"] },
  "discrete": { sublist: 5, related: ["discretely", "discretion", "discretionary", "indiscrete", "indiscretion"] },
  "draft": { sublist: 5, related: ["drafted", "drafting", "drafts", "redraft", "redrafted", "redrafting", "redrafts"] },
  "enable": { sublist: 5, related: ["enabled", "enables", "enabling"] },
  "energy": { sublist: 5, related: ["energetic", "energetically", "energies"] },
  "enforce": { sublist: 5, related: ["enforced", "enforcement", "enforces", "enforcing"] },
  "entity": { sublist: 5, related: ["entities"] },
  "equivalent": { sublist: 5, related: ["equivalence"] },
  "evolve": { sublist: 5, related: ["evolution", "evolutionary", "evolutionist", "evolutionists", "evolved", "evolves", "evolving"] },
  "expand": { sublist: 5, related: ["expanded", "expanding", "expands", "expansion", "expansionism", "expansive"] },
  "expose": { sublist: 5, related: ["exposed", "exposes", "exposing", "exposure", "exposures"] },
  "external": { sublist: 5, related: ["externalisation", "externalise", "externalised", "externalises", "externalising", "externality", "externalization", "externalize", "externalized", "externalizes", "externalizing", "externally"] },
  "facilitate": { sublist: 5, related: ["facilitated", "facilitates", "facilitating", "facilitation", "facilitator", "facilitators", "facilities", "facility"] },
  "fundamental": { sublist: 5, related: ["fundamentally"] },
  "generate": { sublist: 5, related: ["generated", "generates", "generating"] },
  "generation": { sublist: 5, related: ["generations"] },
  "image": { sublist: 5, related: ["imagery", "images"] },
  "liberal": { sublist: 5, related: ["liberalisation", "liberalise", "liberalised", "liberalises", "liberalising", "liberalism", "liberalization", "liberalize", "liberalized", "liberalizes", "liberalizing", "liberally", "liberate", "liberated", "liberates", "liberating", "liberation", "liberations", "liberator", "liberators"] },
  "licence": { sublist: 5, related: ["licences", "license", "licensed", "licenses", "licensing", "unlicensed"] },
  "logic": { sublist: 5, related: ["illogical", "illogically", "logical", "logically", "logician", "logicians"] },
  "margin": { sublist: 5, related: ["marginal", "marginally", "margins"] },
  "medical": { sublist: 5, related: ["medically"] },
  "mental": { sublist: 5, related: ["mentality", "mentally"] },
  "modify": { sublist: 5, related: ["modification", "modifications", "modified", "modifies", "modifying", "unmodified"] },
  "monitor": { sublist: 5, related: ["monitored", "monitoring", "monitors", "unmonitored"] },
  "network": { sublist: 5, related: ["networked", "networking", "networks"] },
  "notion": { sublist: 5, related: ["notions"] },
  "objective": { sublist: 5, related: ["objectively", "objectivity"] },
  "orient": { sublist: 5, related: ["orientate", "orientated", "orientates", "orientating", "orientation", "oriented", "orienting", "orients", "reorient", "reorientation"] },
  "perspective": { sublist: 5, related: ["perspectives"] },
  "precise": { sublist: 5, related: ["imprecise", "precisely", "precision"] },
  "prime": { sublist: 5, related: ["primacy"] },
  "psychology": { sublist: 5, related: ["psychological", "psychologically", "psychologist", "psychologists"] },
  "pursue": { sublist: 5, related: ["pursued", "pursues", "pursuing", "pursuit", "pursuits"] },
  "ratio": { sublist: 5, related: ["ratios"] },
  "reject": { sublist: 5, related: ["rejected", "rejecting", "rejection", "rejections", "rejects"] },
  "revenue": { sublist: 5, related: ["revenues"] },
  "stable": { sublist: 5, related: ["instability", "stabilisation", "stabilise", "stabilised", "stabilises", "stabilising", "stability", "stabilization", "stabilize", "stabilized", "stabilizes", "stabilizing", "unstable"] },
  "style": { sublist: 5, related: ["styled", "styles", "styling", "stylise", "stylised", "stylises", "stylish", "stylising", "stylize", "stylized", "stylizes", "stylizing"] },
  "substitute": { sublist: 5, related: ["substituted", "substitutes", "substituting", "substitution"] },
  "sustain": { sublist: 5, related: ["sustainability", "sustainable", "sustained", "sustaining", "sustains", "sustenance", "unsustainable"] },
  "symbol": { sublist: 5, related: ["symbolic", "symbolically", "symbolise", "symbolised", "symbolises", "symbolising", "symbolism", "symbolize", "symbolized", "symbolizes", "symbolizing", "symbols"] },
  "target": { sublist: 5, related: ["targeted", "targeting", "targets"] },
  "transit": { sublist: 5, related: ["transited", "transiting", "transition", "transitional", "transitions", "transitory", "transits"] },
  "trend": { sublist: 5, related: ["trends"] },
  "version": { sublist: 5, related: ["versions"] },
  "welfare": { sublist: 5, related: [] },
  "whereas": { sublist: 5, related: [] },
  "abstract": { sublist: 6, related: ["abstraction", "abstractions", "abstractly", "abstracts"] },
  "accurate": { sublist: 6, related: ["accuracy", "accurately", "inaccuracies", "inaccuracy", "inaccurate"] },
  "acknowledge": { sublist: 6, related: ["acknowledged", "acknowledgement", "acknowledgements", "acknowledges", "acknowledging"] },
  "aggregate": { sublist: 6, related: ["aggregated", "aggregates", "aggregating", "aggregation"] },
  "allocate": { sublist: 6, related: ["allocated", "allocates", "allocating", "allocation", "allocations"] },
  "assign": { sublist: 6, related: ["assigned", "assigning", "assignment", "assignments", "assigns", "reassign", "reassigned", "reassigning", "reassigns", "unassigned"] },
  "attach": { sublist: 6, related: ["attached", "attaches", "attaching", "attachment", "attachments", "unattached"] },
  "author": { sublist: 6, related: ["authored", "authoring", "authors", "authorship"] },
  "bond": { sublist: 6, related: ["bonded", "bonding", "bonds"] },
  "brief": { sublist: 6, related: ["brevity", "briefed", "briefing", "briefly", "briefs"] },
  "capable": { sublist: 6, related: ["capabilities", "capability", "incapable"] },
  "cite": { sublist: 6, related: ["citation", "citations", "cited", "cites", "citing"] },
  "cooperate": { sublist: 6, related: ["co-operate", "co-operated", "co-operates", "co-operation", "co-operative", "co-operatively", "cooperated", "cooperates", "cooperating", "cooperation", "cooperative", "cooperatively"] },
  "discriminate": { sublist: 6, related: ["discriminated", "discriminates", "discriminating", "discrimination"] },
  "display": { sublist: 6, related: ["displayed", "displaying", "displays"] },
  "diverse": { sublist: 6, related: ["diversely", "diversification", "diversified", "diversifies", "diversify", "diversifying", "diversity"] },
  "domain": { sublist: 6, related: ["domains"] },
  "edit": { sublist: 6, related: ["edited", "editing", "edition", "editions", "editor", "editorial", "editorials", "editors", "edits"] },
  "enhance": { sublist: 6, related: ["enhanced", "enhancement", "enhances", "enhancing"] },
  "estate": { sublist: 6, related: ["estates"] },
  "exceed": { sublist: 6, related: ["exceeded", "exceeding", "exceeds"] },
  "expert": { sublist: 6, related: ["expertise", "expertly", "experts"] },
  "explicit": { sublist: 6, related: ["explicitly"] },
  "federal": { sublist: 6, related: ["federation", "federations"] },
  "fee": { sublist: 6, related: ["fees"] },
  "flexible": { sublist: 6, related: ["flexibility", "inflexibility", "inflexible"] },
  "furthermore": { sublist: 6, related: [] },
  "gender": { sublist: 6, related: ["genders"] },
  "ignorant": { sublist: 6, related: ["ignorance", "ignore", "ignored", "ignores", "ignoring"] },
  "incentive": { sublist: 6, related: ["incentives"] },
  "incidence": { sublist: 6, related: ["incident", "incidentally", "incidents"] },
  "incorporate": { sublist: 6, related: ["incorporated", "incorporates", "incorporating", "incorporation"] },
  "index": { sublist: 6, related: ["indexed", "indexes", "indexing"] },
  "inhibit": { sublist: 6, related: ["inhibited", "inhibiting", "inhibition", "inhibitions", "inhibits"] },
  "initiate": { sublist: 6, related: ["initiated", "initiates", "initiating", "initiation", "initiations", "initiative", "initiatives", "initiator", "initiators"] },
  "input": { sublist: 6, related: ["inputs"] },
  "instruct": { sublist: 6, related: ["instructed", "instructing", "instruction", "instructions", "instructive", "instructor", "instructors", "instructs"] },
  "intelligent": { sublist: 6, related: ["intelligence", "intelligently", "unintelligent"] },
  "interval": { sublist: 6, related: ["intervals"] },
  "lecture": { sublist: 6, related: ["lectured", "lecturer", "lecturers", "lectures", "lecturing"] },
  "migrate": { sublist: 6, related: ["migrant", "migrants", "migrated", "migrates", "migrating", "migration", "migrations", "migratory"] },
  "minimum": { sublist: 6, related: [] },
  "ministry": { sublist: 6, related: ["ministered", "ministerial", "ministering", "ministries"] },
  "motive": { sublist: 6, related: ["motivate", "motivated", "motivates", "motivating", "motivation", "motivations", "motives", "unmotivated"] },
  "neutral": { sublist: 6, related: ["neutralisation", "neutralise", "neutralised", "neutralises", "neutralising", "neutrality", "neutralization", "neutralize", "neutralized", "neutralizes", "neutralizing"] },
  "nevertheless": { sublist: 6, related: [] },
  "overseas": { sublist: 6, related: [] },
  "precede": { sublist: 6, related: ["preceded", "precedence", "precedent", "precedes", "preceding", "unprecedented"] },
  "presume": { sublist: 6, related: ["presumably", "presumed", "presumes", "presuming", "presumption", "presumptions", "presumptuous"] },
  "rational": { sublist: 6, related: ["irrational", "rationalisation", "rationalisations", "rationalise", "rationalised", "rationalises", "rationalising", "rationalism", "rationality", "rationalization", "rationalizations", "rationalize", "rationalized", "rationalizes", "rationally"] },
  "recover": { sublist: 6, related: ["recoverable", "recovered", "recovering", "recovers", "recovery"] },
  "reveal": { sublist: 6, related: ["revealed", "revealing", "reveals", "revelation", "revelations"] },
  "scope": { sublist: 6, related: [] },
  "subsidy": { sublist: 6, related: ["subsidiary", "subsidies", "subsidise", "subsidised", "subsidises", "subsidising", "subsidize", "subsidized", "subsidizes", "subsidizing"] },
  "tape": { sublist: 6, related: ["taped", "tapes", "taping"] },
  "trace": { sublist: 6, related: ["traceable", "traced", "traces", "tracing"] },
  "transform": { sublist: 6, related: ["transformation", "transformations", "transformed", "transforming", "transforms"] },
  "transport": { sublist: 6, related: ["transportation", "transported", "transporter", "transporters", "transporting", "transports"] },
  "underlie": { sublist: 6, related: ["underlay", "underlies", "underlying"] },
  "utilise": { sublist: 6, related: ["utilisation", "utilised", "utiliser", "utilisers", "utilises", "utilising", "utilities", "utility", "utilization", "utilize", "utilized", "utilizes", "utilizing"] },
  "adapt": { sublist: 7, related: ["adaptability", "adaptable", "adaptation", "adaptations", "adapted", "adapting", "adaptive", "adapts"] },
  "adult": { sublist: 7, related: ["adulthood", "adults"] },
  "advocate": { sublist: 7, related: ["advocacy", "advocated", "advocates", "advocating"] },
  "aid": { sublist: 7, related: ["aided", "aiding", "aids", "unaided"] },
  "channel": { sublist: 7, related: ["channelled", "channelling", "channels"] },
  "chemical": { sublist: 7, related: ["chemically", "chemicals"] },
  "classic": { sublist: 7, related: ["classical", "classics"] },
  "comprehensive": { sublist: 7, related: ["comprehensively"] },
  "comprise": { sublist: 7, related: ["comprised", "comprises", "comprising"] },
  "confirm": { sublist: 7, related: ["confirmation", "confirmed", "confirming", "confirms"] },
  "contrary": { sublist: 7, related: ["contrarily"] },
  "convert": { sublist: 7, related: ["conversion", "conversions", "converted", "convertible", "converting", "converts"] },
  "couple": { sublist: 7, related: ["coupled", "couples", "coupling"] },
  "decade": { sublist: 7, related: ["decades"] },
  "definite": { sublist: 7, related: ["definitely", "definitive", "indefinite", "indefinitely"] },
  "deny": { sublist: 7, related: ["deniable", "denial", "denials", "denied", "denies", "denying", "undeniable"] },
  "differentiate": { sublist: 7, related: ["differentiated", "differentiates", "differentiating", "differentiation"] },
  "dispose": { sublist: 7, related: ["disposable", "disposal", "disposed", "disposes", "disposing"] },
  "dynamic": { sublist: 7, related: ["dynamically", "dynamics"] },
  "eliminate": { sublist: 7, related: ["eliminated", "eliminates", "eliminating", "elimination"] },
  "empirical": { sublist: 7, related: ["empirically", "empiricism"] },
  "equip": { sublist: 7, related: ["equipment", "equipped", "equipping", "equips"] },
  "extract": { sublist: 7, related: ["extracted", "extracting", "extraction", "extracts"] },
  "file": { sublist: 7, related: ["filed", "files", "filing"] },
  "finite": { sublist: 7, related: ["infinite", "infinitely"] },
  "foundation": { sublist: 7, related: ["foundations"] },
  "globe": { sublist: 7, related: ["global", "globalisation", "globalization", "globally"] },
  "grade": { sublist: 7, related: ["graded", "grades", "grading"] },
  "guarantee": { sublist: 7, related: ["guaranteed", "guaranteeing", "guarantees"] },
  "hierarchy": { sublist: 7, related: ["hierarchical", "hierarchies"] },
  "identical": { sublist: 7, related: ["identically"] },
  "ideology": { sublist: 7, related: ["ideological", "ideologically", "ideologies"] },
  "infer": { sublist: 7, related: ["inference", "inferences", "inferred", "inferring", "infers"] },
  "innovate": { sublist: 7, related: ["innovated", "innovates", "innovating", "innovation", "innovations", "innovative", "innovator", "innovators"] },
  "insert": { sublist: 7, related: ["inserted", "inserting", "insertion", "inserts"] },
  "intervene": { sublist: 7, related: ["intervened", "intervenes", "intervening", "intervention", "interventions"] },
  "isolate": { sublist: 7, related: ["isolated", "isolates", "isolating", "isolation", "isolationism"] },
  "media": { sublist: 7, related: [] },
  "mode": { sublist: 7, related: ["modes"] },
  "paradigm": { sublist: 7, related: ["paradigms"] },
  "phenomenon": { sublist: 7, related: ["phenomena", "phenomenal"] },
  "priority": { sublist: 7, related: ["priorities", "prioritisation", "prioritise", "prioritised", "prioritises", "prioritising", "prioritization", "prioritize", "prioritized", "prioritizes", "prioritizing"] },
  "prohibit": { sublist: 7, related: ["prohibited", "prohibiting", "prohibition", "prohibitions", "prohibitive", "prohibits"] },
  "publication": { sublist: 7, related: ["publications"] },
  "quote": { sublist: 7, related: ["quotation", "quotations", "quoted", "quotes", "quoting"] },
  "release": { sublist: 7, related: ["released", "releases", "releasing"] },
  "reverse": { sublist: 7, related: ["irreversible", "reversal", "reversals", "reversed", "reverses", "reversible", "reversing"] },
  "simulate": { sublist: 7, related: ["simulated", "simulates", "simulating", "simulation"] },
  "sole": { sublist: 7, related: ["solely"] },
  "somewhat": { sublist: 7, related: [] },
  "submit": { sublist: 7, related: ["submission", "submissions", "submits", "submitted", "submitting"] },
  "successor": { sublist: 7, related: ["succession", "successions", "successive", "successively", "successors"] },
  "survive": { sublist: 7, related: ["survival", "survived", "survives", "surviving", "survivor", "survivors"] },
  "thesis": { sublist: 7, related: ["theses"] },
  "topic": { sublist: 7, related: ["topical", "topics"] },
  "transmit": { sublist: 7, related: ["transmission", "transmissions", "transmits", "transmitted", "transmitting"] },
  "ultimate": { sublist: 7, related: ["ultimately"] },
  "unique": { sublist: 7, related: ["uniquely", "uniqueness"] },
  "visible": { sublist: 7, related: ["invisibility", "invisible", "visibility", "visibly"] },
  "voluntary": { sublist: 7, related: ["voluntarily", "volunteer", "volunteered", "volunteering", "volunteers"] },
  "abandon": { sublist: 8, related: ["abandoned", "abandoning", "abandonment", "abandons"] },
  "accompany": { sublist: 8, related: ["accompanied", "accompanies", "accompaniment", "accompanying", "unaccompanied"] },
  "accumulate": { sublist: 8, related: ["accumulated", "accumulates", "accumulating", "accumulation"] },
  "ambiguous": { sublist: 8, related: ["ambiguities", "ambiguity", "unambiguous", "unambiguously"] },
  "append": { sublist: 8, related: ["appended", "appendices", "appending", "appendix", "appendixes", "appends"] },
  "appreciate": { sublist: 8, related: ["appreciable", "appreciably", "appreciated", "appreciates", "appreciating", "appreciation", "unappreciated"] },
  "arbitrary": { sublist: 8, related: ["arbitrarily", "arbitrariness"] },
  "automate": { sublist: 8, related: ["automated", "automates", "automatic", "automatically", "automating", "automation"] },
  "bias": { sublist: 8, related: ["biased", "biases", "biasing", "unbiased"] },
  "chart": { sublist: 8, related: ["charted", "charting", "charts", "uncharted"] },
  "clarify": { sublist: 8, related: ["clarification", "clarified", "clarifies", "clarifying", "clarity"] },
  "commodity": { sublist: 8, related: ["commodities"] },
  "complement": { sublist: 8, related: ["complementary", "complemented", "complementing", "complements"] },
  "conform": { sublist: 8, related: ["conformability", "conformable", "conformance", "conformation", "conformed", "conforming", "conformist", "conformists", "conformity", "conforms", "non-conformist", "non-conformists", "non-conformity", "nonconformist", "nonconformists", "nonconformity"] },
  "contemporary": { sublist: 8, related: ["contemporaries"] },
  "contradict": { sublist: 8, related: ["contradicted", "contradicting", "contradiction", "contradictions", "contradictory", "contradicts"] },
  "crucial": { sublist: 8, related: ["crucially"] },
  "currency": { sublist: 8, related: ["currencies"] },
  "denote": { sublist: 8, related: ["denotation", "denotations", "denoted", "denotes", "denoting"] },
  "detect": { sublist: 8, related: ["detectable", "detected", "detecting", "detection", "detective", "detectives", "detector", "detectors", "detects"] },
  "deviate": { sublist: 8, related: ["deviated", "deviates", "deviating", "deviation", "deviations"] },
  "displace": { sublist: 8, related: ["displaced", "displacement", "displaces", "displacing"] },
  "drama": { sublist: 8, related: ["dramas", "dramatic", "dramatically", "dramatisation", "dramatisations", "dramatise", "dramatised", "dramatises", "dramatising", "dramatist", "dramatists", "dramatization", "dramatizations", "dramatize", "dramatized", "dramatizes", "dramatizing"] },
  "eventual": { sublist: 8, related: ["eventuality", "eventually"] },
  "exhibit": { sublist: 8, related: ["exhibited", "exhibiting", "exhibition", "exhibitions", "exhibits"] },
  "exploit": { sublist: 8, related: ["exploitation", "exploited", "exploiting", "exploits"] },
  "fluctuate": { sublist: 8, related: ["fluctuated", "fluctuates", "fluctuating", "fluctuation", "fluctuations"] },
  "guideline": { sublist: 8, related: ["guidelines"] },
  "highlight": { sublist: 8, related: ["highlighted", "highlighting", "highlights"] },
  "implicit": { sublist: 8, related: ["implicitly"] },
  "induce": { sublist: 8, related: ["induced", "induces", "inducing", "induction"] },
  "inevitable": { sublist: 8, related: ["inevitability", "inevitably"] },
  "infrastructure": { sublist: 8, related: ["infrastructures"] },
  "inspect": { sublist: 8, related: ["inspected", "inspecting", "inspection", "inspections", "inspector", "inspectors", "inspects"] },
  "intense": { sublist: 8, related: ["intensely", "intenseness", "intensification", "intensified", "intensifies", "intensify", "intensifying", "intension", "intensity", "intensive", "intensively"] },
  "manipulate": { sublist: 8, related: ["manipulated", "manipulates", "manipulating", "manipulation", "manipulations", "manipulative"] },
  "minimise": { sublist: 8, related: ["minimised", "minimises", "minimising", "minimize", "minimized", "minimizes", "minimizing"] },
  "nuclear": { sublist: 8, related: [] },
  "offset": { sublist: 8, related: ["offsets", "offsetting"] },
  "paragraph": { sublist: 8, related: ["paragraphing", "paragraphs"] },
  "plus": { sublist: 8, related: ["pluses"] },
  "practitioner": { sublist: 8, related: ["practitioners"] },
  "predominant": { sublist: 8, related: ["predominance", "predominantly", "predominate", "predominated", "predominates", "predominating"] },
  "prospect": { sublist: 8, related: ["prospective", "prospects"] },
  "radical": { sublist: 8, related: ["radically", "radicals"] },
  "random": { sublist: 8, related: ["randomly", "randomness"] },
  "reinforce": { sublist: 8, related: ["reinforced", "reinforcement", "reinforcements", "reinforces", "reinforcing"] },
  "restore": { sublist: 8, related: ["restoration", "restored", "restores", "restoring"] },
  "revise": { sublist: 8, related: ["revised", "revises", "revising", "revision", "revisions"] },
  "schedule": { sublist: 8, related: ["reschedule", "rescheduled", "reschedules", "rescheduling", "scheduled", "schedules", "scheduling", "unscheduled"] },
  "tense": { sublist: 8, related: ["tensely", "tenser", "tensest", "tension", "tensions"] },
  "terminate": { sublist: 8, related: ["terminal", "terminals", "terminated", "terminates", "terminating", "termination", "terminations"] },
  "theme": { sublist: 8, related: ["thematic", "thematically", "themes"] },
  "thereby": { sublist: 8, related: [] },
  "uniform": { sublist: 8, related: ["uniformity", "uniformly"] },
  "vehicle": { sublist: 8, related: ["vehicles"] },
  "via": { sublist: 8, related: [] },
  "virtual": { sublist: 8, related: ["virtually"] },
  "visual": { sublist: 8, related: ["visualisation", "visualise", "visualised", "visualising", "visualization", "visualize", "visualized", "visualizing", "visually"] },
  "widespread": { sublist: 8, related: [] },
  "accommodate": { sublist: 9, related: ["accommodated", "accommodates", "accommodating", "accommodation"] },
  "analogy": { sublist: 9, related: ["analogies", "analogous"] },
  "anticipate": { sublist: 9, related: ["anticipated", "anticipates", "anticipating", "anticipation", "unanticipated"] },
  "assure": { sublist: 9, related: ["assurance", "assurances", "assured", "assuredly", "assures", "assuring"] },
  "attain": { sublist: 9, related: ["attainable", "attained", "attaining", "attainment", "attainments", "attains", "unattainable"] },
  "behalf": { sublist: 9, related: [] },
  "bulk": { sublist: 9, related: ["bulky"] },
  "cease": { sublist: 9, related: ["ceased", "ceaseless", "ceases", "ceasing"] },
  "coherent": { sublist: 9, related: ["coherence", "coherently", "incoherent", "incoherently"] },
  "coincide": { sublist: 9, related: ["coincided", "coincidence", "coincidences", "coincident", "coincidental", "coincides", "coinciding"] },
  "commence": { sublist: 9, related: ["commenced", "commencement", "commences", "commencing", "recommenced", "recommences", "recommencing"] },
  "compatible": { sublist: 9, related: ["compatibility", "incompatibility", "incompatible"] },
  "concurrent": { sublist: 9, related: ["concurrently"] },
  "confine": { sublist: 9, related: ["confined", "confines", "confining", "unconfined"] },
  "controversy": { sublist: 9, related: ["controversial", "controversially", "controversies", "uncontroversial"] },
  "converse": { sublist: 9, related: ["conversely"] },
  "device": { sublist: 9, related: ["devices"] },
  "devote": { sublist: 9, related: ["devoted", "devotedly", "devotes", "devoting", "devotion", "devotions"] },
  "diminish": { sublist: 9, related: ["diminished", "diminishes", "diminishing", "diminution", "undiminished"] },
  "distort": { sublist: 9, related: ["distorted", "distorting", "distortion", "distortions", "distorts"] },
  "duration": { sublist: 9, related: [] },
  "erode": { sublist: 9, related: ["eroded", "erodes", "eroding", "erosion"] },
  "ethic": { sublist: 9, related: ["ethical", "ethically", "ethics", "unethical"] },
  "format": { sublist: 9, related: ["formats", "formatted", "formatting"] },
  "found": { sublist: 9, related: ["founded", "founder", "founders", "founding", "unfounded"] },
  "inherent": { sublist: 9, related: ["inherently"] },
  "insight": { sublist: 9, related: ["insightful", "insights"] },
  "integral": { sublist: 9, related: [] },
  "intermediate": { sublist: 9, related: [] },
  "manual": { sublist: 9, related: ["manually", "manuals"] },
  "mature": { sublist: 9, related: ["immature", "immaturity", "maturation", "maturational", "matured", "matures", "maturing", "maturity"] },
  "mediate": { sublist: 9, related: ["mediated", "mediates", "mediating", "mediation"] },
  "medium": { sublist: 9, related: [] },
  "military": { sublist: 9, related: [] },
  "minimal": { sublist: 9, related: ["minimalisation", "minimalise", "minimalised", "minimalises", "minimalising", "minimalist", "minimalistic", "minimalists", "minimalization", "minimalize", "minimalized", "minimalizes", "minimalizing", "minimally"] },
  "mutual": { sublist: 9, related: ["mutually"] },
  "norm": { sublist: 9, related: ["norms"] },
  "overlap": { sublist: 9, related: ["overlapped", "overlapping", "overlaps"] },
  "passive": { sublist: 9, related: ["passively", "passivity"] },
  "portion": { sublist: 9, related: ["portions"] },
  "preliminary": { sublist: 9, related: ["preliminaries"] },
  "protocol": { sublist: 9, related: ["protocols"] },
  "qualitative": { sublist: 9, related: ["qualitatively"] },
  "refine": { sublist: 9, related: ["refined", "refinement", "refinements", "refines", "refining"] },
  "relax": { sublist: 9, related: ["relaxation", "relaxed", "relaxes", "relaxing"] },
  "restrain": { sublist: 9, related: ["restrained", "restraining", "restrains", "restraint", "restraints", "unrestrained"] },
  "revolution": { sublist: 9, related: ["revolutionaries", "revolutionary", "revolutionise", "revolutionised", "revolutionises", "revolutionising", "revolutionist", "revolutionists", "revolutionize", "revolutionized", "revolutionizes", "revolutionizing", "revolutions"] },
  "rigid": { sublist: 9, related: ["rigidities", "rigidity", "rigidly"] },
  "route": { sublist: 9, related: ["routed", "routes", "routing"] },
  "scenario": { sublist: 9, related: ["scenarios"] },
  "sphere": { sublist: 9, related: ["spheres", "spherical", "spherically"] },
  "subordinate": { sublist: 9, related: ["subordinates", "subordination"] },
  "supplement": { sublist: 9, related: ["supplementary", "supplemented", "supplementing", "supplements"] },
  "suspend": { sublist: 9, related: ["suspended", "suspending", "suspends", "suspension"] },
  "team": { sublist: 9, related: ["teamed", "teaming", "teams"] },
  "temporary": { sublist: 9, related: ["temporarily"] },
  "trigger": { sublist: 9, related: ["triggered", "triggering", "triggers"] },
  "unify": { sublist: 9, related: ["unification", "unified", "unifies", "unifying"] },
  "violate": { sublist: 9, related: ["violated", "violates", "violating", "violation", "violations"] },
  "vision": { sublist: 9, related: ["visions"] },
  "adjacent": { sublist: 10, related: [] },
  "albeit": { sublist: 10, related: [] },
  "assemble": { sublist: 10, related: ["assembled", "assembles", "assemblies", "assembling", "assembly"] },
  "collapse": { sublist: 10, related: ["collapsed", "collapses", "collapsible", "collapsing"] },
  "colleague": { sublist: 10, related: ["colleagues"] },
  "compile": { sublist: 10, related: ["compilation", "compilations", "compiled", "compiles", "compiling"] },
  "conceive": { sublist: 10, related: ["conceivable", "conceivably", "conceived", "conceives", "conceiving", "inconceivable", "inconceivably"] },
  "convince": { sublist: 10, related: ["convinced", "convinces", "convincing", "convincingly", "unconvinced"] },
  "depress": { sublist: 10, related: ["depressed", "depresses", "depressing", "depression"] },
  "encounter": { sublist: 10, related: ["encountered", "encountering", "encounters"] },
  "enormous": { sublist: 10, related: ["enormity", "enormously"] },
  "forthcoming": { sublist: 10, related: [] },
  "incline": { sublist: 10, related: ["inclination", "inclinations", "inclined", "inclines", "inclining"] },
  "integrity": { sublist: 10, related: [] },
  "intrinsic": { sublist: 10, related: ["intrinsically"] },
  "invoke": { sublist: 10, related: ["invoked", "invokes", "invoking"] },
  "levy": { sublist: 10, related: ["levies"] },
  "likewise": { sublist: 10, related: [] },
  "nonetheless": { sublist: 10, related: [] },
  "notwithstanding": { sublist: 10, related: [] },
  "odd": { sublist: 10, related: ["odds"] },
  "ongoing": { sublist: 10, related: [] },
  "panel": { sublist: 10, related: ["panelled", "panelling", "panels"] },
  "persist": { sublist: 10, related: ["persisted", "persistence", "persistent", "persistently", "persisting", "persists"] },
  "pose": { sublist: 10, related: ["posed", "poses", "posing"] },
  "reluctance": { sublist: 10, related: ["reluctant", "reluctantly"] },
  "so-called": { sublist: 10, related: [] },
  "straightforward": { sublist: 10, related: [] },
  "undergo": { sublist: 10, related: ["undergoes", "undergoing", "undergone", "underwent"] },
  "whereby": { sublist: 10, related: [] },
};
