import { s } from "./seed-lib.mjs";

export default {
  adjacent: s("毗鄰的", "next to something; neighbouring", "The {blank} room is reserved for interviews.", "adjacent", [["adjacent", "to"]]),
  albeit: s("雖然", "although; even if only to a limited extent", "The sample is large, {blank} drawn from a single city.", "albeit"),
  assemble: s("組裝；集合", "bring parts or people together", "The team will {blank} the kit the night before fieldwork.", "assemble", [["assemble", "evidence"]], ["A public {blank} is scheduled in the hall.", "assembly", "名詞"]),
  collapse: s("崩潰", "fall down or fail suddenly", "The coalition may {blank} if the amendment fails.", "collapse", [["collapse", "of"]], ["A sudden {blank} in returns is plotted in Figure 2.", "collapse", "名詞"]),
  colleague: s("同事", "a person one works with in the same organisation", "Please copy a {blank} on every ethics query.", "colleague", [["close", "colleague"]], ["Two {blank} independently coded the files.", "colleagues", "名詞"]),
  compile: s("彙編", "gather materials and put them into one work", "We {blank} a list of every dataset cited in the volume.", "compile", [["compile", "a list"]], ["A {blank} of the circulars is posted online.", "compilation", "名詞"]),
  conceive: s("構想", "form an idea of something in the mind", "The authors {blank} of the archive as a public good.", "conceive", [["conceive", "of"]], ["A {blank} alternative is sketched in the conclusion.", "conceivable", "形容詞"]),
  convince: s("說服", "cause someone to believe that something is true", "The residuals {blank} us that a second term is needed.", "convince", [["convince", "the reader"]], ["A {blank} account of the gap is still missing.", "convincing", "形容詞"]),
  depress: s("壓抑；使蕭條", "push something down in level or mood", "High fees {blank} applications from the poorest decile.", "depress", [["depress", "demand"]], ["A regional {blank} in hiring is noted in section 4.", "depression", "名詞"]),
  encounter: s("遭遇", "meet something, often unexpectedly or as a difficulty", "Coders {blank} the same edge case in every tenth file.", "encounter", [["encounter", "problems"]], ["An early {blank} with the archive shaped the design.", "encounter", "名詞"]),
  enormous: s("巨大的", "extremely large", "An {blank} volume of email attachments exceeded the cap.", "enormous", [["enormous", "impact"]], ["Costs rose {blank} after the currency shift.", "enormously", "副詞"]),
  forthcoming: s("即將到來的；樂於提供的", "about to happen, or willing to give information", "A {blank} erratum will correct the date in Table 2.", "forthcoming", [["forthcoming", "book"]]),
  incline: s("傾向", "lean toward a view or a physical angle", "The board may {blank} toward a shorter instrument.", "incline", [["incline", "to"]], ["That {blank} is stated in the minutes.", "inclination", "名詞"]),
  integrity: s("誠信；完整", "honesty of practice, or the state of being whole", "Data {blank} is checked after every merge.", "integrity", [["academic", "integrity"], ["integrity", "of"]]),
  intrinsic: s("內在的", "belonging to something as an essential part", "Curiosity is treated as an {blank} motive in the model.", "intrinsic", [["intrinsic", "value"], ["intrinsic", "motivation"]], ["The task is {blank} interesting to most of the cohort.", "intrinsically", "副詞"]),
  invoke: s("援引", "appeal to a law, idea, or authority in support of a claim", "The authors {blank} a 1972 circular as precedent.", "invoke", [["invoke", "a principle"]], ["The same statute was {blank} in the later case.", "invoked", "動詞"]),
  levy: s("課徵", "impose and collect a tax or charge, or the charge itself", "The council may {blank} a small fee on late renewals.", "levy", [["levy", "a tax"]], ["Two extra {blank} appear on the invoice.", "levies", "名詞"]),
  likewise: s("同樣地", "in the same way", "Site A used a shorter form; site B did {blank}.", "likewise"),
  nonetheless: s("儘管如此", "in spite of that", "The sample is small; {blank} the pattern is stable.", "nonetheless"),
  notwithstanding: s("儘管", "in spite of a stated fact", "The file is incomplete; the estimate is reported {blank}.", "notwithstanding"),
  odd: s("奇特的；單數的", "strange, or not divisible by two", "An {blank} gap remains between the two official counts.", "odd", [["odd", "case"]], ["The {blank} of completion are listed by faculty.", "odds", "名詞"]),
  ongoing: s("持續進行的", "continuing and not yet finished", "An {blank} audit of the archive is due in June.", "ongoing", [["ongoing", "debate"], ["ongoing", "research"]]),
  panel: s("小組；面板", "a group of people assembled to judge or discuss", "An external {blank} will read every dissertation.", "panel", [["expert", "panel"], ["panel", "discussion"]], ["Two {blank} ran in parallel on Friday.", "panels", "名詞"]),
  persist: s("持續", "continue despite difficulty or opposition", "Late submissions {blank} after the reminder campaign.", "persist", [["persist", "in"]], ["{blank} of the error after cleaning is noted below.", "Persistence", "名詞"]),
  pose: s("構成；提出", "present a problem, question, or risk", "Missing dates {blank} a threat to the timeline.", "pose", [["pose", "a challenge"], ["pose", "a question"]], ["The same dilemma was {blank} in the 1998 review.", "posed", "動詞"]),
  reluctance: s("不情願", "unwillingness to do something", "Staff {blank} to share raw files is discussed in section 5.", "reluctance", [["reluctance", "to"]], ["A {blank} minority declined the follow-up.", "reluctant", "形容詞"]),
  "so-called": s("所謂的", "used to name something in a doubtful or conventional way", "The {blank} shortcut produced duplicate identifiers.", "so-called"),
  straightforward: s("直截的", "easy to understand or simple to carry out", "The deposit steps are {blank} once the checklist is followed.", "straightforward", [["straightforward", "task"]]),
  undergo: s("經歷", "experience a process, often one that is demanding", "Every file must {blank} a second identifier check.", "undergo", [["undergo", "change"]], ["The building has {blank} two refits since 2010.", "undergone", "動詞"]),
  whereby: s("藉以", "by which means; according to which", "A protocol was agreed {blank} each site uses the same script.", "whereby"),
};
